### ISSUE TITLE
启动后ping 114.114.114.114不通

### ISSUE THREAD

**Issue by tony1016** [Kr328/clash-tun-for-linux#3]
ip route：
default via 172.31.80.1 dev wlxec172f78b954 proto dhcp metric 600 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
172.31.80.0/20 dev wlxec172f78b954 proto kernel scope link src 172.31.85.19 metric 600 
172.31.255.252/30 dev clash0 proto kernel scope link src 172.31.255.253 linkdown 
182.0.0.0/8 via 182.119.207.254 dev enp14s0 proto static metric 100 
182.119.207.0/24 dev enp14s0 proto kernel scope link src 182.119.207.121 metric 100

ip rule:
0:	from all lookup local 
32758:	from all uidrange 65534-65535 goto 32766
32759:	from all to 172.31.255.253/30 goto 32767
32760:	from all to 127.0.0.0/8 goto 32766
32761:	from all to 10.0.0.0/8 goto 32766
32762:	from all to 192.168.0.0/16 goto 32766
32763:	from all to 224.0.0.0/4 goto 32766
32764:	from all to 172.16.0.0/12 goto 32766
32765:	from all lookup 354 
32766:	from all lookup main 
32767:	from all lookup default 

但是网络不通

**Comment by Kr328** [comment]
预期行为
