### ISSUE TITLE
没有看明白，你的配置中的clash0这个tun，是如何和clash配置文件中的tun关联的呢？

### ISSUE THREAD

**Issue by tony1016** [Kr328/clash-tun-for-linux#4]
似乎clash启动的tun名称为utun，而你配置文件里是clash0，这两者是如何关联的呢？？

**Comment by Kr328** [comment]
![image](https://user-images.githubusercontent.com/39107975/82985440-9ce9f080-a026-11ea-8d85-2019114f2bb2.png)

看清楚 upstream 了吗

**Comment by tony1016** [comment]
> ![image](https://user-images.githubusercontent.com/39107975/82985440-9ce9f080-a026-11ea-8d85-2019114f2bb2.png)
> 
> 看清楚 upstream 了吗

哦，这样子，明白了
